### ISSUE TITLE
[Feature Suggestion] Use bit-torrent protocol to make mod downloads faster

### ISSUE THREAD

**Issue by TiagoTiago** [TheHellBox/KISS-multiplayer#101]
It would get much faster when downloading separate pieces from different people at the same time; and since previously downloaded mods stay even after leaving a server, we could even be downloading from people that are currently in other servers, or even just playing single-player with KissMP still enabled.

**Comment by TheHellBox** [comment]
It's a bad solution to this problem. Not only it creates a lot of potential security risks, it also won't make mod downloading much faster. Slow mod downloading speed is not a problem of protocol, but rather the implementation.
Also this kind of technique would require strong P2P implementation

**Comment by TiagoTiago** [comment]
The GUI runs on some sort of Chromium derivative, right? Would it be able to run WebTorrent, which can be run from inside web browsers?

**Comment by TheHellBox** [comment]
As I've mentioned earlier, there're no significant benefits of using bit torrent over traditional centralized downloading in our application

**Comment by TiagoTiago** [comment]
> As I've mentioned earlier, there're no significant benefits of using bit torrent over traditional centralized downloading in our application

Are you saying the bottleneck is client-side software? Wouldn't that also benefit from replacing the client-side download system with WebTorrent's download code even if the speed would somehow be indistinguishable from a direct single-piece download?
