### ISSUE TITLE
[Bug] vehicles[player:getCurrentVehicle()] is nil after player exits and re-enters vehicles

### ISSUE THREAD

**Issue by CheezusChrust** [TheHellBox/KISS-multiplayer#104]
If a player leaves their vehicle using the "Enter/Exit Vehicle" bind, and then re-enters any other vehicle through said bind, or through tab, their entry in the vehicles table will be nil until they spawn a new vehicle or replace their current one.

This does not happen when switching vehicles directly with the tab key, it only happens with the "Enter/Exit Vehicle" feature.

**Comment by vulcan-dev** [comment]
I reported this a while back but I hope it gets fixed soon
