### ISSUE TITLE
Issues when using with native Linux port

### ISSUE THREAD

**Issue by SnoutBug** [TheHellBox/KISS-multiplayer#117]
On the native Linux port, the mod loads fine and I'm able to connect to servers. I'm seeing other players as well  but they are not moving. The console prints this error analogously.
```
 37.84020|E|libbeamng.lua.V| *** FATAL LUA ERROR: [string "string"]:1: attempt to index global 'kiss_vehicle' (a nil value)
 37.84021|E|libbeamng.lua.V| =============== Stack Traceback >> START >>
 37.84021|E|libbeamng.lua.V| (1) main chunk of string at line 1
 37.84021|E|libbeamng.lua.V| --------------- << END <<
 37.84022|E|libbeamng.lua.V| *** while executing this line: kiss_vehicle.update_transform_info()
 37.84022|E|libbeamng.lua.V| *** in chunk: string
```
Player name-tags move as well, but only when not in direct vicinity.

**Comment by SnoutBug** [comment]
Replacing all occurrences of 'KISSMultiplayer.zip' with 'kissmultiplayer.zip' fixes this error message, but there is still nothing moving

**Comment by SnoutBug** [comment]
Works now for some reason. Only thing I'm missing are engine sounds while the horn of others works fine. I guess it's safe to close this now.

**Comment by Dummiesman** [comment]
Thanks for getting to the cause of this. I'll fix it soon enough!
