### ISSUE TITLE
[Gameplay - Vehicles] Player cannot get out from any car

### ISSUE THREAD

**Issue by KiraTodorova** [TheHellBox/KISS-multiplayer#129]
**Description:**
Admin/Player cannot leave the car if it is heavily modded or entirely vanilla.

**Steps to repro:**
1. Host a Modded server
2. Join said server
3. Load any vehicle
4. Press 'F'
5. Observe the result

**Expected result:**
The player/Admin can get out of the vehicle.

**Actual Result:**
The player/Admin cannot get out of the vehicle.

**Notes:**
Tested on Gavril Roamer (Heavily Modded) and Gavril Blueback /Fully Modded).
Found on a modded server.

**Comment by vulcan-dev** [comment]
Must be an issue on your side, I've never seen anyone not being able to exit a vehicle.
There is one bug however, if you get out and back in, the server will not register any new vehicle to you. This has been a bug since walk mode was added.

**Comment by KiraTodorova** [comment]
I will make a full test in regards to this encounter and will come back with more info. More info may imply:

- A test for both modded and vanilla vehicles
- A test for both Modded and Vanilla KissMP Servers
- A test with other players
- More descriptive scenarios
- Better steps to reproduce
- And repro values from max times tested and times it happens

**Comment by KiraTodorova** [comment]
Okidoki! I did as I suggested and I found out some stuff! I will make a new entry with updated info :)
