### ISSUE TITLE
Push new update for v0.21

### ISSUE THREAD

**Issue by Koenvh1** [TheHellBox/KISS-multiplayer#41]
I saw you uploaded 0.2.0.2 for v0.21, but the last commit seems to be from 19 days ago. Can you push those changes, so I can build them from the source?

**Comment by TheHellBox** [comment]
Changes only affect client side(lua), you don't have to build them.
They introduce temporary workaround that affect performance, and the issue is caused by new BeamNG bug. We will wait for developers to fix the issue, so I don't want to push this workaround to git

**Comment by Koenvh1** [comment]
Ah, understood. I see what you mean, and I think I can figure out how that broke based on the patch notes for v0.21. I just was not sure whether something changed serverside as well.

I take it that you are already in contact with the BeamNG then? 
I hope they fix it soon, because KissMP is frankly an amazing project 👍
