### ISSUE TITLE
Can't use custom/mod maps?

### ISSUE THREAD

**Issue by mistopportunity** [TheHellBox/KISS-multiplayer#43]
I can join my server with any of the default maps just fine, but for any of the maps I've downloaded through the in-game UI (and enabled them) don't work even though I can join them normally through the freeroam menu. If my map is in the `Documents\BeamNG.drive\mods\repo` folder I can use it and beam reports the level loaded as `levels/name_of_the_map/info.json` in the console, but when I use the same map string in the server, loading fails with this error: `expanded mission file is invalid - nil from /levels/name_of_the_map/info.json`

I have found a way to make it work by unpacking the mod and putting it in `Documents\BeamNG.drive\levels` folder but I'm feeling like this isn't correct or intuitive. I'm not sure how this would work for other players that have already downloaded the mod normally, would they have to download again?

**Comment by TheHellBox** [comment]
Put your map in /mods folder in the server directory
