### ISSUE TITLE
Cannot connect to my own server (others can)

### ISSUE THREAD

**Issue by KeemoLV** [TheHellBox/KISS-multiplayer#44]
So, basically, I run kissmp-server, it's on and working. Others can join, but not me. Chat shows "Failed to confirm connection. Check if bridge is running." And bridge indeed is running. I can join other servers just fine, while mine is open. Also, I get "Client is trying to connect to the server" in my server log. Any ideas?

**Comment by KeemoLV** [comment]
Tested with 0.20.2 and 0.21, same results.

**Comment by TheHellBox** [comment]
Connect using direct connect, to 127.0.0.1

**Comment by WhiteHusky** [comment]
Little more information:
The server list provides **public** IPs to connect with and if you attempt to connect to yourself with your own **public** IP it'll result in a failed connection. This is called a [hairpin](https://en.wikipedia.org/wiki/Hairpinning) and many modems do not support doing this.
