### ISSUE TITLE
[SUGGESTION] External server information system

### ISSUE THREAD

**Issue by Amplar** [TheHellBox/KISS-multiplayer#47]
External server information browser. Increase population of servers via people able to see what's going on without having to fire up the game. Helps with servers that have their population based on....population of the server. 
Doesn't need to launch the game and join the server- just a tool for information.

**Comment by Bartixxx32** [comment]
You can make yourself using this json
http://51.210.135.45:3692/

**Comment by JakobJakobJakob2** [comment]
I made an external serverlist using the API Bartixx posted a while ago if you're interested 
[github page](https://github.com/JakobJakobJakob2/KissMP-Serverlist)
