### ISSUE TITLE
[SUGGESTION] Client occlusion - optimize framerate

### ISSUE THREAD

**Issue by Amplar** [TheHellBox/KISS-multiplayer#49]
System to manually or automatically occlude other client vehicles via chat command or distance to help out lower spec CPUs.
Probably best if clients have an ID that's visible in the player list to avoid having to type actual nametags for the commands.

Display nametag and indicator that they are hidden on their position, but do not spawn their vehicle until you specify you wish to see them. Helps when your framerate is being annihilated or someone is using a very intensive vehicle and you are generally not interacting with them.
A system to disable collision between the hidden target and yourself would probably need to be at play as well to prevent being griefed by an invisible vehicle.

**Comment by Bartixxx32** [comment]
I think you cant disable collisions becouse almost all is rendering your client, server technically is syncing player position and car steering like gearbox throttle and steering, but thats my opinion

**Comment by TheHellBox** [comment]
This can partly be implemented with server addons
