### ISSUE TITLE
Client on Linux

### ISSUE THREAD

**Issue by sniperlucian** [TheHellBox/KISS-multiplayer#52]
running beamng on steam. 
installed the mod into the folder. 
starting the ./kissmp-bridge in command line - shows "Bridege is running!"

starting beamng via steam 
game shows that the mod is installed 

BUT I cant find any drop down in game window, where I could locate a game server etc....

what can I do ?

**Comment by Those45Ninjas** [comment]
Appears to be working perfectly fine on a mostly fresh install of Popos 20.04 running beamng under steamplay/proton.

**Comment by sniperlucian** [comment]
reinstalled beamng via steam - droped kissmultplayer.zip again and its working now. 

maybe beamMP messed with the installation - which I tried before.
