### ISSUE TITLE
kissmp-bridge.exe detected as Trojan.Fsysna.mpl on Jiangmin

### ISSUE THREAD

**Issue by AnimMouse** [TheHellBox/KISS-multiplayer#53]
VirusTotal:
[kissmp-bridge.exe](https://www.virustotal.com/gui/file/43bef932f5fed9561cb34b43dde1b183d2b307f01b89c379302b75fc16191ef3/detection)
[KissMP-0_2_0_2.zip](https://www.virustotal.com/gui/file/0c633cb95060d5d571e79616e067dcdc78e41620572795e71de09b740f679de7/detection)

**Comment by TheHellBox** [comment]
We don't really care what antivirus software says about our binaries, as we can't influence this in any way. The project is open source - so it's trojan/virus free in any case
