### ISSUE TITLE
Error when joining a server.

### ISSUE THREAD

**Issue by asdfgpio** [TheHellBox/KISS-multiplayer#61]
Bridge is running!
Attempt to connect to a server
Connection!
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src\voice_chat.rs:37:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Any ideas?

**Comment by AsciiJakob** [comment]
Reading [line 37](https://github.com/TheHellBox/KISS-multiplayer/blob/c55d300ab28e73e3bc173d8067f9dde30a0e81c4/kissmp-bridge/src/voice_chat.rs#L37),
it looks like it failed to get your default microphone/input device. This shouldn't stop the program but it does so it's an issue.
Could you provide more information that could possibly be of help to Hellbox once he's online? A screenshot of your input device menu (assuming you're using windows) could be helpful.

**Comment by TheHellBox** [comment]
I should remove this unwrap tbh, will do

**Comment by asdfgpio** [comment]
Do you need any more information?

**Comment by WhiteHusky** [comment]
@asdfgpio Don't think we need anything. And sorry if the force-pushes caused mail-spam.

**Comment by WhiteHusky** [comment]
But I reckon if you actually had an audio input device and it was set as your default device but still caused an error then we'd like to know.

Incoming PR will let you connect if you're missing a default device (somehow) or just don't have one.
