### ISSUE TITLE
Bridge Closing When Joining Server (Audio Input Error)

### ISSUE THREAD

**Issue by IonicOwl** [TheHellBox/KISS-multiplayer#67]
Bridge appears to run fine initially, but closes itself when trying to join a server.
I ran bridge from the command prompt so I could catch the error without it closing the window:

`Bridge is running!
Attempt to connect to a server
Connection!
No default audio input device available for voice chat.
Check your OS's settings and verify you have a device available.`

This is a fresh install of Windows, and I haven't configured any microphone/input devices yet.  Regardless, if this is intentional and not a bug, I'm not sure this should be a requirement to be able to join a server if the user doesn't intend on using voice chat features.

**BeamNG.drive version** - 0.22.1.0.11673
**KissMP version** - 0.4.2
**Bridge version** - latest
**OS** - Windows 10 64-bit - 20H2 - Build 19042.906

**Comment by TheHellBox** [comment]
It's a bug and it's a weird one. It doesn't make any sense tbh, and it seems like it's windows only issue.
Regardless, I'll have to fix that

**Comment by TheHellBox** [comment]
A workaround is to create some kind of a fake audio input device on your system

**Comment by IonicOwl** [comment]
Just for completeness, I've plugged in my USB headset and the bridge seems happy now:
`Bridge is running!
Attempt to connect to a server
Connection!
Using default audio input device: Microphone (Corsair Vengeance 1500)
Audio stream configured with the following settings:
        Channels: 2
        Sample rate: SampleRate(48000)
        Buffer size: Default
Use it with a key bound in BeamNG.Drive`

**Comment by WhiteHusky** [comment]
> @IonicOwl 
> Just for completeness, I've plugged in my USB headset and the bridge seems happy now:
> [...]

PR has been sent out, but I think it was more because you didn't have any outputs. And we were not handling when there were no outputs available ergo the program panics.
