### ISSUE TITLE
Bridge closes when connecting to server if no microphone is connected

### ISSUE THREAD

**Issue by Chipskate** [TheHellBox/KISS-multiplayer#69]
As stated in the title, the KissMP bridge program closes if you attempt to connect to any server with no microphone connected, see screenshot:
![powershell_2021-04-09_23-38-28](https://user-images.githubusercontent.com/6464713/114243920-cafdc800-998d-11eb-8865-660f73dc7b8f.png)
This is on Windows 10, I haven't tried it on Linux.

**Comment by WhiteHusky** [comment]
Belated, but having issues replicating.
I've tried different disabled device configurations to emulate a disconnected input device or output device and the bridge works fine regardless.

You are welcomed to [pull from my dev branch for configurations](https://github.com/WhiteHusky/KISS-multiplayer/tree/dev), obtain your choice of VSCode or Codium, the rust toolchain, and [CodeLLB to launch](https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb) to see if it'll catch an exception or some kind of thread for us to work on.

**Comment by Chipskate** [comment]
I managed to compile a debug executable and ran in the CodeLLB debugger, this is what I got:
Terminal output:
![Code_2021-04-13_02-35-01](https://user-images.githubusercontent.com/6464713/114480471-e4f41080-9c02-11eb-9e81-a9508f103e9d.png)
Debug console:
![Code_2021-04-13_02-34-51](https://user-images.githubusercontent.com/6464713/114480095-1f10e280-9c02-11eb-85c6-b0eeda35d3e2.png)
Call stack (throws exception in NdrClientCall3):
![Code_2021-04-13_02-41-00](https://user-images.githubusercontent.com/6464713/114480110-2801b400-9c02-11eb-9bdf-10522307cc86.png)
NdrClientCall3 exception dump: https://pastebin.com/qx5fnWUL (I've highlighted the exception breakpoint)
Here's a screenshot of the audio input devices in the control panel:
![rundll32_2021-04-13_02-53-15](https://user-images.githubusercontent.com/6464713/114480739-706da180-9c03-11eb-8de9-8b0217c13fe2.png)
Please let me know if there's any more info you want, and I'll get to it tomorrow afternoon.

**Comment by WhiteHusky** [comment]
This is really unusual. It's more information but it's perhaps a bit too dense.

Not helping is that `NdrClientCall3` is entirely undocumented and my [only lead is that it's dealing with Remote Procedure Call](http://filelog.net/func/NdrClientCall3). Maybe something tokio based.

Perhaps when I'm more available over the weekend or sometime this week we could make use of Live Share on Visual Studio and start a session to poke at the program.

**Comment by TheHellBox** [comment]
I have an idea on how we can try to fix it, let me do one thing

**Comment by TheHellBox** [comment]
@Chipskate Check if master branch still has this issue, I've made a commit a few minutes ago.
Instead of destroying a thread if audio device wasn't found, I just prevent thread from being created in the first case

**Comment by Chipskate** [comment]
@TheHellBox Been trying out the latest build for a while, can confirm that it works flawlessely now!

**Comment by TheHellBox** [comment]
@Chipskate Does it output "No default audio input device found" error?

**Comment by Chipskate** [comment]
@TheHellBox Yeah, same warning message except it doesn't crash this time.

**Comment by TheHellBox** [comment]
Cool, will make a new release today then
