### ISSUE TITLE
Lag problem

### ISSUE THREAD

**Issue by Mecagoenlosguiris** [TheHellBox/KISS-multiplayer#79]
When I'm playing with my friend we spawn very far from each other, but that's not the problem.
The problem is that when we finally get closer, the server hits a tug and I start to see my friend very lagged.
I have made the server myself, what could be the problem?

**Comment by KeemoLV** [comment]
You get lag when you get closer because of vehicle distance setting. Turn it off, and lag spike won't happen, but your FPS will be lower.

**Comment by Mecagoenlosguiris** [comment]
Where i can turn it off? Sorry im very noob in kissmp... hehehehe

**Comment by vulcan-dev** [comment]
> Where i can turn it off? Sorry im very noob in kissmp... hehehehe

Hello, in the KissMP Window there will be a settings button all the way on the right. When you select it, you should see the view distance slider and toggle button to enable/disable it. Go ahead and disable it.
