### ISSUE TITLE
Proton 6.3-4 crashes

### ISSUE THREAD

**Issue by Hacker1245** [TheHellBox/KISS-multiplayer#82]
Proton 6.3-4 seems to crash with the newest KissMP version, most often seen while modifying vehicles (deleting, respawning).
I'm using Manjaro Linux with the mesa open source drivers, kernel 5.12. The game does not crash when playing without the mod installed.

**Comment by TheHellBox** [comment]
Full proton compatibility is not our responsibility. Proton 5.13-6 is properly functioning, stay on it
