### ISSUE TITLE
Game Crashes when Rendering 2+ Vehicles at the Same Time

### ISSUE THREAD

**Issue by ZekeHyena** [TheHellBox/KISS-multiplayer#83]
**I noticed whenever I Shift+C around the see other people,** whenever I would get over to them, my game would freeze and crash. I don't know if this is an only me type deal, but whenever 2 or more people come within a certain distance of me, their vehicles will render in. Why do their vehicles not stay rendered in no matter what distance they are away? I believe this rendering thing is causing my game to crash, as its only whenever I'm rendering 2+ vehicles from other players, my game will freeze up and crash.

Sorry for any grammatical errors. I'm bad at English.

**Comment by AsciiJakob** [comment]
You can turn off the vehicle render distance in the KissMP settings. Just click on the settings tab in the KissMP window
